/** https://github.com/w3c/webappsec-permissions-policy/blob/main/features.md */
export const iframeAllowDirective = [
  /** Standardized Features */
  "accelerometer",
  "ambient-light-sensor",
  "autoplay",
  "battery",
  "bluetooth",
  "camera",
  "ch-ua",
  "ch-ua-arch",
  "ch-ua-bitness",
  "ch-ua-full-version",
  "ch-ua-full-version-list",
  "ch-ua-mobile",
  "ch-ua-model",
  "ch-ua-platform",
  "ch-ua-platform-version",
  "ch-ua-wow64",
  "cross-origin-isolated",
  "display-capture",
  "encrypted-media",
  "execution-while-not-rendered",
  "execution-while-out-of-viewport",
  "fullscreen",
  "geolocation",
  "gyroscope",
  "hid",
  "idle-detection",
  "keyboard-map",
  "magnetometer",
  "microphone",
  "midi",
  "navigation-override",
  "payment",
  "picture-in-picture",
  "publickey-credentials-get",
  "screen-wake-lock",
  "serial",
  "sync-xhr",
  "usb",
  "web-share",
  "xr-spatial-tracking",

  /** Proposed Features */
  "clipboard-read",
  "clipboard-write",
  "gamepad",
  "shared-autofill",
  "speaker-selection",

  /** Experimental Features */
  "browsing-topics",
  "conversion-measurement",
  "focus-without-user-activation",
  "join-ad-interest-group",
  "local-fonts",
  "run-ad-auction",
  "sync-script",
  "trust-token-redemption",
  "unload",
  "vertical-scroll",
  "window-placement",

  /** Retired Features */
  // 'document-domain',
]
  .map((ele) => `${ele} *`)
  .join("; ");
